# backup mikrotik to sftp
- hosts: all
  connection: network_cli
  gather_facts: true
  #**************** 
  # {{ ansible_date_time.date }} ansible system system date 
  
  tasks:
  - name: create backup
    routeros_command:
      commands: '/system backup save name=bcp-{{inventory_hostname}}'
    register: cmdout
  - debug:
       var: cmdout.stdout_lines
  - name: create cfg
    routeros_command:
      commands: '/export file=cfg-{{inventory_hostname}}'
    register: cmdout
  - debug:
       var: cmdout.stdout_lines
  - name: copy backup to sftp
    routeros_command:
      commands: '/tool fetch url="sftp://192.168.168.235/upload/bcp-{{ ansible_date_time.date }}-{{inventory_hostname}}.backup" src-path=bcp-{{inventory_hostname}}.backup user=USER mode=ftp password=PASS upload=yes'
    register: cmdout
  - name: copy config to sftp
    routeros_command: 
      commands: '/tool fetch url="sftp://192.168.168.235/upload/cfg-{{ ansible_date_time.date }}-{{inventory_hostname}}.rsc" src-path=cfg-{{inventory_hostname}}.rsc user=USER mode=ftp password=PASS upload=yes'
    register: cmdout
  - debug:
       var: cmdout.stdout_lines
